### ISSUE TITLE
未搜索到匹配的视频文件

### ISSUE THREAD

**Issue by ttys000** [ForgQi/biliup-rs#20]
在配置文件中使用绝对或相对路径都不行，提示未搜索到匹配的视频文件。

```yaml
line: bda2
limit: 3
streamers:
  ~/c/*.mp4:
    copyright: 1
    source: # 转载来源
    tid: 231 # 投稿分区
    cover: "" # 视频封面
    title: "2021 年秋季学期 ICS 课程"
    desc_format_id: 0
    desc: "2021 年秋季学期 ICS 课程"
    dolby: 0 # 杜比音效
    dynamic: ""
    subtitle:
      open: 0
      lan: ""
    tag: "计算机基础, C 语言"
    dtime: ~
    open_subtitle: false
```
